CREATE DATABASE IF NOT EXISTS hirenext;
USE hirenext;

CREATE TABLE IF NOT EXISTS recruiter (
  rid VARCHAR(20) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  addjob BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE recruiter
ADD COLUMN IF NOT EXISTS addjob BOOLEAN NOT NULL DEFAULT FALSE;
